export const SUBSCRIPTION_PLANS = [
  {
    id: "trial",
    name: "7-Day Trial",
    price: "₹1",
    period: "for 7 days",
    originalPrice: "₹199",
    discount: "Try Premium",
    features: [{ text: "Experience the app, Share feedback", included: true }],
  },
  {
    id: "basic",
    name: "Basic",
    price: "₹999/-",
    period: "Once a year, taxes extra",
    originalPrice: "₹1999/-",
    discount: "50% OFF",
    features: [
      { text: "Create profile", included: true },
      { text: "Browse profiles", included: true },
      { text: "Limited likes per day", included: true },
      { text: "Basic matching", included: true },
      { text: "See your liked profiles", included: true },
      { text: "Message anyone", included: true },
    ],
  },
  {
    id: "premium",
    name: "Premium",
    price: "₹1999/-",
    period: "Once a year, taxes extra",
    originalPrice: "₹4999",
    discount: "60% OFF",
    popular: true,
    features: [
      { text: "Profile verification badge as Premium ", included: true },
      { text: "Show your lifestyle as Premium ", included: true },
      { text: "Add premium quality photos", included: true },
      { text: "See who liked you", included: true },
      { text: "Unlimited likes", included: true },
      { text: "Message anyone", included: true },
      { text: "Advanced filters", included: true },
    ],
  },
];
