export const SUBSCRIPTION_PLANS = [
  {
    id: "trial",
    name: "7-Day Trial",
    price: "₹1",
    period: "for 7 days",
    originalPrice: "₹199",
    discount: "Try Premium",
    features: [{ text: "Experience the app, Share feedback", included: true }],
  },
  {
    id: "basic",
    name: "Basic",
    price: "₹999/-",
    period: "Once a year, taxes extra",
    originalPrice: "₹1999/-",
    discount: "50% OFF",
    features: [
      { text: "'Premium' Badge on Profile", included: true },
      { text: "Express your lifestyle as Premium", included: true },
      { text: "See your liked Profile", included: true },
      { text: "Message directly to find your soul partner", included: true },
    ],
  },
  {
    id: "premium",
    name: "Premium",
    price: "₹1999/-",
    period: "Once a year, taxes extra",
    originalPrice: "₹3999",
    discount: "50% OFF",
    popular: true,
    features: [
      { text: "'Premium' Badge on Profile", included: true },
      { text: "Express your lifestyle as Premium", included: true },
      { text: "High-quality photo uploads", included: true },
      { text: "See who liked you", included: true },
      { text: "Advanced filters", included: true },
      { text: "Message directly to find your soul partner", included: true },
    ],
  },
];
