import { AppStackParamList, TabParamList } from "../../../navigation/types";
import { NativeStackNavigationProp } from "@react-navigation/native-stack";
import { BottomTabNavigationProp } from "@react-navigation/bottom-tabs";
import { CompositeNavigationProp } from "@react-navigation/native";


// 🔹 Profile info used inside chat partner preview
export interface ChatPartnerProfile {
  id: string;      // otherUserId
  fullName: string;
  photo?: string;  // first photo (optional)
  age?: number;
}

// 🔹 One row in "recentChatPartners" list
export interface RecentChatPartner {
  roomId: string;           // generated by backend
  lastMessage: string;      // latest message text
  lastMessageAt: string;    // ISO string timestamp
  otherUser: ChatPartnerProfile | null; // may be null if profile not found
  unreadCount: number;      // unread for current user
}

// 🔹 For chat messages inside a room
export interface ChatMessage {
  id: string;        // Firestore doc id
  text: string;
  senderId: string;
  receiverId: string;
  roomId: string;
  createdAt: Date;   // converted to Date on frontend
  status: "sent" | "delivered" | "read";
  isSent?: boolean;  // convenience: true if senderId === currentUserId
}

export interface MessagesScreenNavigationProp extends CompositeNavigationProp<
  BottomTabNavigationProp<TabParamList, "Messages">,
  NativeStackNavigationProp<AppStackParamList>
  > { }

  // types/messages.ts
export interface UserBannerItem {
  id: string;
  name: string;
  photo?: string;
  age?: number;
  lastMessage?: string;
  lastMessageAt?: Date | string;
  unreadCount?: number;
}