import * as SplashScreen from "expo-splash-screen";
import React, { useEffect } from "react";
import { useAuth } from "../context/AuthContext";
import { NavigationContainer } from "@react-navigation/native";
import { createNativeStackNavigator } from "@react-navigation/native-stack";
import { RootStackParamList } from "./types";
import AppNavigator from "./AppNavigator";
import AuthNavigator from "./AuthNavigator";
import UserInfoScreen from "../features/auth/screens/UserInfoScreen";
import { DatabaseProvider } from "../context/DatabaseContext";

SplashScreen.preventAutoHideAsync();

const Stack = createNativeStackNavigator<RootStackParamList>();

export default function RootNavigator() {
  const { user, authLoading } = useAuth();

  useEffect(() => {
    async function hide() {
      if (!authLoading) {
        setTimeout(async () => {
          try {
            await SplashScreen.hideAsync();
          } catch (e) {}
        }, 100);
      }
    }
    hide();
  }, [authLoading]);

  if (authLoading) return null;

  const isProfileIncomplete = user && !user.displayName;

  return (
    <DatabaseProvider>
      <NavigationContainer>
        <Stack.Navigator screenOptions={{ headerShown: false }}>
          {!user ? (
            <Stack.Screen name="Auth" component={AuthNavigator} />
          ) : isProfileIncomplete ? (
            <Stack.Screen name="UserInfo" component={UserInfoScreen} />
          ) : (
            <Stack.Screen name="App" component={AppNavigator} />
          )}
        </Stack.Navigator>
      </NavigationContainer>
    </DatabaseProvider>
  );
}

// import * as SplashScreen from "expo-splash-screen";
// import React, { useEffect } from "react";
// import { View, Text, Button } from "react-native";
// import { useAuth } from "../context/AuthContext";
// import { NavigationContainer } from "@react-navigation/native";
// import { createNativeStackNavigator } from "@react-navigation/native-stack";
// import { RootStackParamList } from "./types";
// import AppNavigator from "./AppNavigator";
// import AuthNavigator from "./AuthNavigator";
// import UserInfoScreen from "../features/auth/screens/UserInfoScreen";

// // Database & Migrations imports
// import { db, resetDatabase } from "@/db/client";
// import { useMigrations } from "drizzle-orm/expo-sqlite/migrator";
// import migrations from "../../drizzle/migrations"; // Generated by drizzle-kit

// SplashScreen.preventAutoHideAsync();

// const Stack = createNativeStackNavigator<RootStackParamList>();

// export default function RootNavigator() {
//   const { user, authLoading } = useAuth();

//   // 🎯 Run Drizzle migrations
//   const { success: migrationsSuccess, error: migrationError } = useMigrations(
//     db,
//     migrations,
//   );

//   // Always hide Splash Screen once Auth and Migrations resolve (success OR failure)
//   useEffect(() => {
//     async function hideSplash() {
//       if (!authLoading && (migrationsSuccess || migrationError)) {
//         try {
//           await SplashScreen.hideAsync();
//         } catch (e) {}
//       }
//     }
//     hideSplash();
//   }, [authLoading, migrationsSuccess, migrationError]);

//   // 1. Check for Migration Errors FIRST (before blocking on !migrationsSuccess)
//   if (migrationError) {
//     return (
//       <View
//         style={{
//           flex: 1,
//           justifyContent: "center",
//           alignItems: "center",
//           padding: 20,
//           backgroundColor: "#fff",
//         }}
//       >
//         <Text
//           style={{
//             color: "red",
//             fontSize: 16,
//             textAlign: "center",
//             marginBottom: 16,
//           }}
//         >
//           Database migration failed: {migrationError.message}
//         </Text>
//         <Button
//           title="Wipe Local DB & Reset"
//           onPress={() => {
//             resetDatabase();
//             // Force app reload or state reset
//           }}
//         />
//       </View>
//     );
//   }

//   // 2. Block UI rendering only while loading
//   if (authLoading || !migrationsSuccess) {
//     return null;
//   }

//   const isProfileIncomplete = user && !user.displayName;

//   return (
//     <NavigationContainer>
//       <Stack.Navigator screenOptions={{ headerShown: false }}>
//         {!user ? (
//           <Stack.Screen name="Auth" component={AuthNavigator} />
//         ) : isProfileIncomplete ? (
//           <Stack.Screen name="UserInfo" component={UserInfoScreen} />
//         ) : (
//           <Stack.Screen name="App" component={AppNavigator} />
//         )}
//       </Stack.Navigator>
//     </NavigationContainer>
//   );
// }
